include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

variables:
  GIT_DEPTH: "1"

default:
  # docker.io/koalaman/shellcheck-alpine:stable
  image: registry.gitlab.com/cki-project/containers/mirror/shellcheck-alpine:stable

shell check cki:
  stage: test
  before_script:
    - shellcheck --version
    - "# Mock beakerlib.sh to avoid source import errors:"
    - mkdir /usr/share/beakerlib
    - touch /usr/share/beakerlib/beakerlib.sh
  script:
    - shellcheck --external-sources --format=gcc cki_*/*.sh
  rules:
    - changes:
      - "cki_*/*.sh"

shell check runtests:
  stage: test
  before_script:
    - shellcheck --version
  script:
    - find -name '*.sh' -exec shellcheck --severity=error -f gcc {} +
  rules:
    - changes:
      - "**/*.sh"
