hugemmap01 hugemmap01 -s #nr_hpage#
hugemmap02 hugemmap02 -s #nr_hpage#
hugemmap04 hugemmap04 -s #nr_hpage#

hugemmap05 hugemmap05 -a #size#
hugemmap05_m hugemmap05 -m -a #size#
hugemmap05_s hugemmap05 -s -a #size#
hugemmap05_ms hugemmap05 -m -s -a #size#

hugemmap06 hugemmap06
hugemmap07 hugemmap07
hugemmap08 hugemmap08
hugemmap09 hugemmap09
hugemmap10 hugemmap10
hugemmap11 hugemmap11
hugemmap12 hugemmap12
hugemmap13 hugemmap13
hugemmap14 hugemmap14
hugemmap15 hugemmap15
hugemmap16 hugemmap16
hugemmap17 hugemmap17
hugemmap18 hugemmap18
hugemmap19 hugemmap19
hugemmap20 hugemmap20
hugemmap21 hugemmap21
hugemmap22 hugemmap22
hugemmap23 hugemmap23
hugemmap24 hugemmap24
hugemmap25 hugemmap25
hugemmap26 hugemmap26
hugemmap27 hugemmap27
hugemmap28 hugemmap28
hugemmap29 hugemmap29
hugemmap30 hugemmap30
hugemmap31 hugemmap31
hugemmap32 hugemmap32

hugeshmat01 hugeshmat01 -s #nr_hpage# -i 5
hugeshmat02 hugeshmat02 -s #nr_hpage# -i 5
hugeshmat03 hugeshmat03 -s #nr_hpage# -i 5
hugeshmat04 hugeshmat04 -i 5
hugeshmat05 hugeshmat05 -i 5

hugeshmctl01 hugeshmctl01 -s #nr_hpage# -i 5
hugeshmctl02 hugeshmctl02 -s #nr_hpage# -i 5
hugeshmctl03 hugeshmctl03 -s #nr_hpage# -i 5

hugeshmdt01 hugeshmdt01 -s #nr_hpage# -i 5

hugeshmget01 hugeshmget01 -s #nr_hpage# -i 10
hugeshmget02 hugeshmget02 -s #nr_hpage# -i 10
hugeshmget03 hugeshmget03 -s #nr_hpage# -i 10
hugeshmget05 hugeshmget05 -s #nr_hpage# -i 10

hugefallocate01 hugefallocate01
hugefallocate02 hugefallocate02

hugefork01 hugefork01
hugefork02 hugefork02
