#!/usr/bin/expect -f

log_file output.log

set force_conservative 1  ;# set to 1 to force conservative mode even if
			  ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set timeout 600
spawn virt-install --name vm1 --memory 1024 --transient --disk none --boot useserial=on --cdrom /usr/share/ipxe/ipxe.iso --nographic
match_max 100000
expect -exact "\rPress Ctrl-B for the iPXE command line..."
send -- ""
expect -exact "iPXE> "
send -- "ifconf\r"
if {$env(TEST_PING_CMD) == 1} {
	expect -exact "iPXE> "
	send -- "ping --count 5 HYPERVISOR_HOSTNAME\r"
}
expect -exact "iPXE> "
send -- "chain http://HYPERVISOR_HOSTNAME/boot.txt\r"
expect -exact "dracut:/# "
send -- "uname -r\r"
expect -exact "KERNEL_VERSION"
expect -exact "dracut:/# "
send -- "poweroff\r"
expect eof
