#!/bin/bash

# based on /usr/share/restraint/plugins/task_run.d/25_environment
. /usr/share/restraint/plugins/helpers
. /usr/share/restraint/plugins/cki_helpers

# Don't run from PLUGINS
if [ -n "$RSTRNT_NOPLUGINS" ]; then
    exec "$@"
    exit 0
fi

rstrnt_info "*** Running Plugin: $0"

if [[ -e "${CURRENT_TASK_PATH}" ]]; then
    # Make sure we don't try to run another task if system is already running one.
    # Workaround for https://gitlab.com/cki-project/upt/-/issues/99
    # We can't compare with RSTRNT_TASKID, because the reserve job that UPT uses to reserve a beaker machine
    # also runs the plugins, at least the recipe ID from UPT runs and the reservation is the same
    CURRENT_RECIPE_ID=$(ls ${CURRENT_TASK_PATH})
    if [[ -n "${CURRENT_RECIPE_ID}" ]] && [[ "${CURRENT_RECIPE_ID}" != "${RSTRNT_RECIPEID}" ]]; then
        rstrnt-report-result "${RSTRNT_TASKNAME}" FAIL
        echo "Aborting task $RSTRNT_TASKID from recipe ${RSTRNT_RECIPEID} as system expects to run tests for recipe ${CURRENT_RECIPE_ID}"
        rstrnt-abort --server "$RSTRNT_RECIPE_URL/tasks/$RSTRNT_TASKID/status"
        exit 1
    fi
fi

# it seems when running restraint as standalone the value can increment
# even if there was no reboot, like if a connection is interrupted
# https://gitlab.com/cki-project/upt/-/issues/99
mkdir -p "${CURRENT_TASK_PATH}/${RSTRNT_RECIPEID}/${RSTRNT_TASKID}"
# saves the boot information everytime the task starts or continues
who -b >> "${CURRENT_TASK_PATH}/${RSTRNT_RECIPEID}/${RSTRNT_TASKID}/bootinfo"
# overwrite RSTRNT_REBOOTCOUNT
RSTRNT_REBOOTCOUNT=$(cat "${CURRENT_TASK_PATH}/${RSTRNT_RECIPEID}/${RSTRNT_TASKID}/bootinfo" | uniq | wc -l)
# start counting from 0
RSTRNT_REBOOTCOUNT=$((${RSTRNT_REBOOTCOUNT}-1))
exec "$@"
